import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import ConvexClientProvider from '@/providers/ConvexClientProvider';
import { TooltipProvider } from '@/components/ui/tooltip';
import { Toaster } from '@/components/ui/sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'TV Chat App',
	description: 'Generated by TV',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className='scrollbar-thumb-white/20 scrollbar-track-white/20 bg-[#1A1A1A]'>
			<body className={inter.className}>
				<ConvexClientProvider>
					<TooltipProvider>{children}</TooltipProvider>
					<Toaster richColors />
				</ConvexClientProvider>
			</body>
		</html>
	);
}
